name: Build MaterialBinLoader

on:
  push:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
        fail-fast: false
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25c
          add-to-path: false
        
      - name: Build
        run: ./build.sh
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Create Release and Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
<<<<<<< HEAD
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
=======
          tag_name: ${{ github.run_number }}
          name: Release ${{ github.run_number }}
>>>>>>> parent of c4d8b93 (test)
          body: Support 1.21.50 release and 1.21.60.21 preview
          draft: false
          prerelease: false
          files: |
            ./build/libmaterialbinloader-arm.so
            ./build/libmaterialbinloader-arm64.so
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
