name: Build MaterialBinLoader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with: 
          ndk-version: r21e
          add-to-path: true
      
      - name: Build
        run: .\build.bat
